# .renpy-tools/archive_utils.py
import os
import sys
import io
import glob
import math
import zlib
import zipfile
import hashlib
import hmac
import secrets
import datetime
from typing import Tuple, List, Dict, Optional

from env_utils import (
    load_env,
    get_encryption_key,
    get_pack_warn_mb,
    get_pack_limit_mb,
    get_obfuscate_paths,
    get_aliases,
)

MAGIC_HEADER = b"RPT1"
SALT_SIZE = 16
IV_SIZE = 16
TAG_SIZE = 32
PBKDF2_ITERATIONS = 100000


def _derive_keys(passphrase: str, salt: bytes) -> Tuple[bytes, bytes]:
    """Derives encryption key and HMAC key using PBKDF2-HMAC-SHA256."""
    derived = hashlib.pbkdf2_hmac("sha256", passphrase.encode("utf-8"), salt, PBKDF2_ITERATIONS, dklen=64)
    return derived[:32], derived[32:]


def _keystream_block(enc_key: bytes, iv: bytes, counter: int) -> bytes:
    """Generates a 32-byte pseudo-random keystream block using HMAC-SHA256 counter mode."""
    counter_bytes = counter.to_bytes(8, byteorder="big")
    return hmac.new(enc_key, iv + counter_bytes, hashlib.sha256).digest()


def encrypt_data(data: bytes, passphrase: str) -> bytes:
    """
    Encrypts data using PBKDF2-HMAC-SHA256 keystream stream cipher (Encrypt-then-MAC).
    Returns binary payload: MAGIC(4) + SALT(16) + IV(16) + MAC(32) + CIPHERTEXT
    """
    salt = secrets.token_bytes(SALT_SIZE)
    iv = secrets.token_bytes(IV_SIZE)
    enc_key, mac_key = _derive_keys(passphrase, salt)

    ciphertext = bytearray()
    block_size = 32
    num_blocks = math.ceil(len(data) / block_size)

    for i in range(num_blocks):
        block = data[i * block_size : (i + 1) * block_size]
        ks = _keystream_block(enc_key, iv, i)
        for b, k in zip(block, ks):
            ciphertext.append(b ^ k)

    ciphertext_bytes = bytes(ciphertext)
    auth_tag = hmac.new(mac_key, iv + ciphertext_bytes, hashlib.sha256).digest()

    return MAGIC_HEADER + salt + iv + auth_tag + ciphertext_bytes


def decrypt_data(encrypted_payload: bytes, passphrase: str) -> bytes:
    """
    Decrypts binary payload produced by encrypt_data.
    Validates magic header and HMAC-SHA256 authentication tag.
    """
    min_len = len(MAGIC_HEADER) + SALT_SIZE + IV_SIZE + TAG_SIZE
    if len(encrypted_payload) < min_len:
        raise ValueError("Invalid encrypted payload: Data is too short.")

    header = encrypted_payload[:4]
    if header != MAGIC_HEADER:
        raise ValueError(f"Invalid archive format: Header magic mismatch ({header!r}).")

    offset = 4
    salt = encrypted_payload[offset : offset + SALT_SIZE]
    offset += SALT_SIZE

    iv = encrypted_payload[offset : offset + IV_SIZE]
    offset += IV_SIZE

    expected_tag = encrypted_payload[offset : offset + TAG_SIZE]
    offset += TAG_SIZE

    ciphertext = encrypted_payload[offset:]

    enc_key, mac_key = _derive_keys(passphrase, salt)

    computed_tag = hmac.new(mac_key, iv + ciphertext, hashlib.sha256).digest()
    if not hmac.compare_digest(expected_tag, computed_tag):
        raise ValueError("Decryption failed: Incorrect encryption key or corrupted archive payload.")

    plaintext = bytearray()
    block_size = 32
    num_blocks = math.ceil(len(ciphertext) / block_size)

    for i in range(num_blocks):
        block = ciphertext[i * block_size : (i + 1) * block_size]
        ks = _keystream_block(enc_key, iv, i)
        for b, k in zip(block, ks):
            plaintext.append(b ^ k)

    return bytes(plaintext)


def resolve_source_target(project_dir: str, args: List[str]) -> Tuple[str, str]:
    """
    Resolves source and target paths from command line arguments or .env aliases.
    Supports:
        python manage.py pack <alias_name>
        python manage.py pack <source> <target>
    """
    if not args:
        raise ValueError("Missing parameters. Provide <source> <target> or a configured <alias_name>.")

    aliases = get_aliases(project_dir)

    # Check if first argument is a defined alias
    alias_key = args[0].strip().lower()
    if alias_key in aliases:
        src, dst = aliases[alias_key]
        print(f"[Alias] Resolved alias '{alias_key}' -> source: '{src}', target: '{dst}'")
        return src, dst

    if len(args) < 2:
        available_aliases = ", ".join(aliases.keys()) if aliases else "None"
        raise ValueError(
            f"Expected 2 parameters (<source> <target>) or a valid alias name. "
            f"Given: {args}. Configured aliases: [{available_aliases}]"
        )

    return args[0], args[1]


def is_backup_dir(dir_name: str) -> bool:
    """Checks if a directory is a local backup folder generated by unpack."""
    return dir_name.startswith("rpt-bkp-")


def pack_assets(project_dir: str, args: List[str]) -> None:
    """
    Packs files from source directory tree into target encrypted or unencrypted archives per folder node.
    """
    source_raw, target_raw = resolve_source_target(project_dir, args)

    source_dir = os.path.abspath(source_raw if os.path.isabs(source_raw) else os.path.join(project_dir, source_raw))
    target_dir = os.path.abspath(target_raw if os.path.isabs(target_raw) else os.path.join(project_dir, target_raw))

    if not os.path.exists(source_dir):
        raise ValueError(f"Source directory does not exist: {source_dir}")

    enc_key = get_encryption_key(project_dir)
    warn_mb = get_pack_warn_mb(project_dir)
    limit_mb = get_pack_limit_mb(project_dir)
    obfuscate = get_obfuscate_paths(project_dir)

    if not enc_key:
        print("[Notice] RPT_ENCRYPTION_KEY is not set in .env. Archives will be created without encryption (.zip).")
    else:
        print("[Pack] Encryption key active. Creating encrypted archives (.zip.enc).")

    packed_count = 0
    total_files_packed = 0

    for root, dirs, files in os.walk(source_dir):
        # Skip backup folders and hidden directories
        dirs[:] = [d for d in dirs if not is_backup_dir(d) and not d.startswith(".")]

        # Filter out hidden files
        valid_files = [f for f in files if not f.startswith(".")]
        if not valid_files:
            continue

        rel_path = os.path.relpath(root, source_dir)
        rel_parts = rel_path.split(os.sep) if rel_path != "." else []

        # Check if any parent part was a backup dir
        if any(is_backup_dir(p) for p in rel_parts):
            continue

        # Check size threshold for this single folder node
        node_uncompressed_bytes = sum(os.path.getsize(os.path.join(root, f)) for f in valid_files)
        node_mb = node_uncompressed_bytes / (1024 * 1024)

        folder_label = os.path.basename(source_dir) if rel_path == "." else os.path.basename(root)

        if node_mb > limit_mb:
            raise ValueError(
                f"[ERROR] Archive '{folder_label}' content size ({node_mb:.2f} MB) exceeds maximum limit "
                f"({limit_mb:.2f} MB). Packing aborted."
            )

        if node_mb > warn_mb:
            print(
                f"[WARNING] Archive '{folder_label}' content size ({node_mb:.2f} MB) exceeds warning threshold "
                f"({warn_mb:.2f} MB)."
            )

        # Determine target output subpath
        if obfuscate and rel_path != ".":
            obf_parts = [hashlib.sha256(p.encode("utf-8")).hexdigest()[:16] for p in rel_parts]
            dest_rel_dir = os.path.join(*obf_parts)
            archive_stem = hashlib.sha256(folder_label.encode("utf-8")).hexdigest()[:16]
        else:
            dest_rel_dir = rel_path if rel_path != "." else ""
            archive_stem = folder_label

        dest_folder = os.path.join(target_dir, dest_rel_dir)
        os.makedirs(dest_folder, exist_ok=True)

        ext = ".zip.enc" if enc_key else ".zip"
        archive_path = os.path.join(dest_folder, f"{archive_stem}{ext}")

        # Create zip payload in memory
        mem_zip = io.BytesIO()
        with zipfile.ZipFile(mem_zip, "w", zipfile.ZIP_DEFLATED) as zf:
            for f in sorted(valid_files):
                file_path = os.path.join(root, f)
                # Store file in zip with relative path inside folder
                zf.write(file_path, arcname=f)

        raw_zip_data = mem_zip.getvalue()

        if enc_key:
            output_payload = encrypt_data(raw_zip_data, enc_key)
        else:
            output_payload = raw_zip_data

        with open(archive_path, "wb") as f_out:
            f_out.write(output_payload)

        packed_count += 1
        total_files_packed += len(valid_files)
        print(f"  -> Packed {len(valid_files)} files into '{os.path.relpath(archive_path, project_dir)}' ({node_mb:.2f} MB)")

    print(f"[Success] Packing complete! Created {packed_count} archive(s) containing {total_files_packed} total file(s).")


def unpack_assets(project_dir: str, args: List[str]) -> None:
    """
    Unpacks archives from source directory tree back into target folder structure.
    Performs SHA-256 comparison and creates rpt-bkp-<timestamp> backups for modified existing files.
    """
    source_raw, target_raw = resolve_source_target(project_dir, args)

    source_dir = os.path.abspath(source_raw if os.path.isabs(source_raw) else os.path.join(project_dir, source_raw))
    target_dir = os.path.abspath(target_raw if os.path.isabs(target_raw) else os.path.join(project_dir, target_raw))

    if not os.path.exists(source_dir):
        raise ValueError(f"Source archive directory does not exist: {source_dir}")

    enc_key = get_encryption_key(project_dir)
    timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")

    unpacked_count = 0
    backed_up_count = 0
    restored_count = 0

    for root, dirs, files in os.walk(source_dir):
        dirs[:] = [d for d in dirs if not is_backup_dir(d) and not d.startswith(".")]

        archive_files = [f for f in files if f.endswith(".zip") or f.endswith(".zip.enc")]
        if not archive_files:
            continue

        rel_path = os.path.relpath(root, source_dir)

        for arch in sorted(archive_files):
            arch_path = os.path.join(root, arch)
            with open(arch_path, "rb") as f_in:
                file_bytes = f_in.read()

            if arch.endswith(".zip.enc"):
                if not enc_key:
                    raise ValueError(
                        f"[ERROR] Found encrypted archive '{os.path.relpath(arch_path, project_dir)}' but RPT_ENCRYPTION_KEY "
                        f"is missing from .env. Decryption impossible."
                    )
                zip_bytes = decrypt_data(file_bytes, enc_key)
            else:
                zip_bytes = file_bytes

            dest_folder = os.path.join(target_dir, rel_path) if rel_path != "." else target_dir

            with zipfile.ZipFile(io.BytesIO(zip_bytes), "r") as zf:
                for zip_name in zf.namelist():
                    extracted_data = zf.read(zip_name)
                    target_file_path = os.path.join(dest_folder, zip_name)
                    target_file_dir = os.path.dirname(target_file_path)
                    os.makedirs(target_file_dir, exist_ok=True)

                    # Content comparison & differential backup
                    if os.path.exists(target_file_path):
                        with open(target_file_path, "rb") as f_existing:
                            existing_bytes = f_existing.read()

                        existing_hash = hashlib.sha256(existing_bytes).digest()
                        extracted_hash = hashlib.sha256(extracted_data).digest()

                        if existing_hash != extracted_hash:
                            # File differs! Create backup
                            backup_dir = os.path.join(target_file_dir, f"rpt-bkp-{timestamp}")
                            os.makedirs(backup_dir, exist_ok=True)
                            backup_file_path = os.path.join(backup_dir, zip_name)

                            with open(backup_file_path, "wb") as f_bkp:
                                f_bkp.write(existing_bytes)

                            backed_up_count += 1
                            print(f"  [BACKUP] Existing file '{zip_name}' differed -> Backed up to 'rpt-bkp-{timestamp}/'")

                    with open(target_file_path, "wb") as f_out:
                        f_out.write(extracted_data)

                    restored_count += 1

            unpacked_count += 1

    print(
        f"[Success] Unpacking complete! Processed {unpacked_count} archive(s), "
        f"restored {restored_count} file(s), created {backed_up_count} backup(s)."
    )
